name: platform_file_url
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.platform_file_url
        pluginClass: PlatformFileUrlPlugin
      ios:
        pluginClass: PlatformFileUrlPlugin
      windows:
        pluginClass: PlatformFileUrlPlugin
      macos:
        pluginClass: PlatformFileUrlPlugin
